# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "cryptd" ];
  boot.initrd.luks.devices."crypted" = {
    device = "/dev/disk/by-uuid/9a39e3d0-5513-42eb-91e3-3f589442b4b2";
    preLVM = true;
  };
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/vg-root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/87D5-2AA0";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/Windows" =
    { device = "/dev/disk/by-uuid/D84E24C44E249CEE";
      fsType = "ntfs3";
      options = [ "uid=1000" "gid=100" "rw" "umask=000" "nofail" ];
    };

  fileSystems."/Files" =
    { device = "/dev/disk/by-uuid/506AD7406AD72210";
      fsType = "ntfs3";
      options = [ "uid=1000" "gid=100" "rw" "umask=000" "nofail" ];
    };

  fileSystems."/Linux" =
    { device = "/dev/disk/by-uuid/8C6688B96688A614";
      fsType = "ntfs3";
      options = [ "uid=1000" "gid=100" "rw" "umask=000" "nofail" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
